application: tstview-alpha
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /report
  script: report.app

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /loading.gif
  static_files: static/images/ajax-loader.gif
  upload: static/images/ajax-loader.gif

- url: /stylesheet.css
  static_files: static/templates/stylesheet.css
  upload: static/templates/stylesheet.css
  
- url: /.*
  script: console.app
  
libraries:
- name: jinja2
  version: latest

error_handlers:

  - error_code: over_quota
    file: recursos/over_quota.html
